# Generated by Django 5.0.3 on 2024-03-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
